module.exports = {
  SURVEYS_RECEIVED: "SURVEYS_RECEIVED",
  SURVEY_RECEIVED: "SURVEY_RECEIVED",
  SURVEY_REMOVED: "SURVEY_REMOVED",
  SURVEY_UPDATED: "SURVEY_UPDATED",
  SURVEY_RECEIVED_FOR_EDIT: "SURVEY_RECEIVED_FOR_EDIT",
  CLEAR_SURVEY_TO_EDIT: "CLEAR_SURVEY_TO_EDIT"
};
